name: aplicacion_noticias
description: Aplicación de noticias con Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Manejo de estado
  provider: ^6.1.1

  # Peticiones HTTP
  http: ^1.2.1

  # Íconos y diseño
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
